/*
 * Generated by @dgwnu/ng-joint-schematics
 */
import { StandardCircle } from './standard-circle';

describe('StandardCircle', () => {
  it('should create an instance', () => {
    expect(new StandardCircle()).toBeTruthy();
  });
});